version: '3'
services: 
  backend:
    platform: linux/x86_64 
    container_name: 'python'
    build:
      dockerfile: '.docker/Dockerfile'
    volumes: 
      - ./:/app
  oracle: 
    platform: linux/x86_64
    container_name: 'oracle'
    image: oraclelinux:6  # Base image for Oracle Linux 6
    volumes:
      - ./oracle-data:/opt/oracle  # Optional: Mount a volume for Oracle data